// Generated by https://quicktype.io

import { FilterValue } from "./Breadcrum";

export interface SearchResult {
    site_id:                   SiteID;
    country_default_time_zone: string;
    query:                     string;
    paging:                    Paging;
    results:                   Products[];
    sort:                      Sort;
    available_sorts:           Sort[];
    filters:                   Filter[];
    available_filters:         AvailableFilter[];
}

export interface AvailableFilter {
    id:     string;
    name:   string;
    type:   string;
    values: AvailableFilterValue[];
}

export interface AvailableFilterValue {
    id:      string;
    name:    string;
    results: number;
}

export interface Sort {
    id:   string;
    name: string;
}

export interface Filter {
    id:     string;
    name:   string;
    type:   string;
    values: FilterValue[];
}

export interface Paging {
    total:           number;
    primary_results: number;
    offset:          number;
    limit:           number;
}

export interface Products {
    id:                   string;
    title:                string;
    condition:            Condition;
    thumbnail_id:         string;
    catalog_product_id:   null | string;
    listing_type_id:      ListingTypeID;
    permalink:            string;
    buying_mode:          BuyingMode;
    site_id:              SiteID;
    category_id:          CategoryID;
    domain_id:            DomainID;
    thumbnail:            string;
    currency_id:          CurrencyID;
    order_backend:        number;
    price:                number;
    original_price:       number | null;
    sale_price:           null;
    sold_quantity:        number;
    available_quantity:   number;
    official_store_id:    number | null;
    use_thumbnail_id:     boolean;
    accepts_mercadopago:  boolean;
    tags:                 ResultTag[];
    shipping:             Shipping;
    stop_time:            string;
    seller:               Seller;
    seller_address:       SellerAddress;
    address:              Address;
    attributes:           Attribute[];
    installments:         null;
    winner_item_id:       null;
    catalog_listing?:     boolean;
    discounts:            null;
    promotions:           any[];
    inventory_id:         null;
    official_store_name?: string;
    variation_id?:        string;
    variation_filters?:   VariationFilter[];
    variations_data?:     { [key: string]: VariationsDatum };
}

export interface Address {
    state_id:   StateID;
    state_name: StateName;
    city_id:    string;
    city_name:  string;
}

export enum StateID {
    UyMa = "UY-MA",
    UyMo = "UY-MO",
    UyRv = "UY-RV",
}

export enum StateName {
    Maldonado = "Maldonado",
    Montevideo = "Montevideo",
    Rivera = "Rivera",
}

export interface Attribute {
    id:                   ID;
    name:                 AttributeName;
    value_id:             null | string;
    value_name:           null | string;
    attribute_group_id:   AttributeGroupID;
    attribute_group_name: AttributeGroupName;
    value_struct:         Struct | null;
    values:               AttributeValue[];
    source:               number;
    value_type:           ValueType;
}

export enum AttributeGroupID {
    Others = "OTHERS",
}

export enum AttributeGroupName {
    Otros = "Otros",
}

export enum ID {
    AlphanumericModel = "ALPHANUMERIC_MODEL",
    Brand = "BRAND",
    ItemCondition = "ITEM_CONDITION",
    Line = "LINE",
    Model = "MODEL",
    Submodel = "SUBMODEL",
    Weight = "WEIGHT",
}

export enum AttributeName {
    CondiciónDelÍtem = "Condición del ítem",
    Línea = "Línea",
    Marca = "Marca",
    Modelo = "Modelo",
    ModeloAlfanumérico = "Modelo alfanumérico",
    Peso = "Peso",
    Submodelo = "Submodelo",
}

export interface Struct {
    number: number;
    unit:   Unit;
}

export enum Unit {
    Kg = "kg",
}

export enum ValueType {
    List = "list",
    NumberUnit = "number_unit",
    String = "string",
}

export interface AttributeValue {
    id:     null | string;
    name:   null | string;
    struct: Struct | null;
    source: number;
}

export enum BuyingMode {
    BuyItNow = "buy_it_now",
}

export enum CategoryID {
    Mlu6344 = "MLU6344",
}

export enum Condition {
    New = "new",
}

export enum CurrencyID {
    Usd = "USD",
    Uyu = "UYU",
}

export enum DomainID {
    MluGameConsoles = "MLU-GAME_CONSOLES",
}

export enum ListingTypeID {
    Bronze = "bronze",
    GoldSpecial = "gold_special",
}

export interface Seller {
    id:                 number;
    nickname:           string;
    car_dealer:         boolean;
    real_estate_agency: boolean;
    _:                  boolean;
    registration_date:  string;
    tags:               SellerTag[];
    car_dealer_logo:    string;
    permalink:          string;
    seller_reputation:  SellerReputation;
    eshop?:             Eshop;
}

export interface Eshop {
    eshop_id:         number;
    seller:           number;
    nick_name:        string;
    eshop_status_id:  number;
    site_id:          SiteID;
    eshop_experience: number;
    eshop_rubro:      EshopRubro | null;
    eshop_locations:  EshopLocation[];
    eshop_logo_url:   string;
}

export interface EshopLocation {
    state:        City;
    city:         City;
    country:      City;
    neighborhood: City;
}

export interface City {
    id: null | string;
}

export interface EshopRubro {
    category_id: string;
    id:          string;
    name:        string;
}

export enum SiteID {
    Mlu = "MLU",
}

export interface SellerReputation {
    level_id:            LevelID | null;
    power_seller_status: PowerSellerStatus | null;
    transactions:        Transactions;
    metrics:             Metrics;
}

export enum LevelID {
    The3_Yellow = "3_yellow",
    The4_LightGreen = "4_light_green",
    The5_Green = "5_green",
}

export interface Metrics {
    sales:                 Sales;
    claims:                Cancellations;
    delayed_handling_time: Cancellations;
    cancellations:         Cancellations;
}

export interface Cancellations {
    period:    CancellationsPeriod;
    rate:      number;
    value:     number;
    excluded?: Excluded;
}

export interface Excluded {
    real_value: number;
    real_rate:  number;
}

export enum CancellationsPeriod {
    The120Days = "120 days",
    The365Days = "365 days",
}

export interface Sales {
    period:    CancellationsPeriod;
    completed: number;
}

export enum PowerSellerStatus {
    Gold = "gold",
    Platinum = "platinum",
    Silver = "silver",
}

export interface Transactions {
    canceled:  number;
    completed: number;
    period:    TransactionsPeriod;
    ratings:   Ratings;
    total:     number;
}

export enum TransactionsPeriod {
    Historic = "historic",
}

export interface Ratings {
    negative: number;
    neutral:  number;
    positive: number;
}

export enum SellerTag {
    Brand = "brand",
    Eshop = "eshop",
    LargeSeller = "large_seller",
    MediumSeller = "medium_seller",
    MediumSellerAdvanced = "medium_seller_advanced",
    MessagesAsSeller = "messages_as_seller",
    Mshops = "mshops",
    Normal = "normal",
}

export interface SellerAddress {
    comment:      string;
    address_line: string;
    id:           null;
    latitude:     null;
    longitude:    null;
    country:      Sort;
    state:        Sort;
    city:         Sort;
}

export interface Shipping {
    store_pick_up: boolean;
    free_shipping: boolean;
    logistic_type: LogisticType;
    mode:          Mode;
    tags:          ShippingTag[];
    promise:       null;
}

export enum LogisticType {
    DropOff = "drop_off",
}

export enum Mode {
    Me2 = "me2",
}

export enum ShippingTag {
    FSThresholdMluUSDJul2021 = "fs_threshold_mlu_USD_jul2021",
    MandatoryFreeShipping = "mandatory_free_shipping",
    SelfServiceIn = "self_service_in",
    SelfServiceOut = "self_service_out",
}

export enum ResultTag {
    BestSellerCandidate = "best_seller_candidate",
    CartEligible = "cart_eligible",
    CatalogListingEligible = "catalog_listing_eligible",
    DraggedBidsAndVisits = "dragged_bids_and_visits",
    GoodQualityPicture = "good_quality_picture",
    GoodQualityThumbnail = "good_quality_thumbnail",
    ImmediatePayment = "immediate_payment",
    LoyaltyDiscountEligible = "loyalty_discount_eligible",
    PoorQualityPicture = "poor_quality_picture",
    PoorQualityThumbnail = "poor_quality_thumbnail",
    ShippingGuaranteed = "shipping_guaranteed",
}

export enum VariationFilter {
    Color = "COLOR",
}

export interface VariationsDatum {
    thumbnail:    string;
    ratio:        string;
    name:         VariationsDatumName;
    pictures_qty: number;
}

export enum VariationsDatumName {
    Blanco = "Blanco",
    BlancoNegro = "Blanco/Negro",
}
